// Generated by starc from system.star, recordings.star, music.star. Do not edit.
// Read with ndb.js: readNdb(buffer, NDB_SCHEMAS.<name>).
export const NDB_SCHEMAS = {
  "system": {
    "hash": 3543000558,
    "path": "/sdcard/db/system.ndb",
    "collections": {
      "1": {
        "name": "state",
        "key": "string",
        "cached": true,
        "fields": {
          "1": {
            "name": "speaker_volume",
            "type": "i32",
            "default": 80
          },
          "2": {
            "name": "mic_gain_db",
            "type": "f32",
            "default": 60.0
          },
          "3": {
            "name": "led_color",
            "type": "rgb",
            "default": 0
          },
          "4": {
            "name": "led_mode",
            "type": "u8",
            "default": 0
          },
          "5": {
            "name": "autoplay",
            "type": "bool",
            "default": true
          },
          "6": {
            "name": "cache_downloads",
            "type": "bool",
            "default": false
          }
        }
      },
      "2": {
        "name": "settings",
        "key": "string",
        "cached": true,
        "fields": {
          "1": {
            "name": "timezone",
            "type": "string",
            "default": "UTC"
          },
          "2": {
            "name": "gemini_model",
            "type": "string",
            "default": ""
          },
          "3": {
            "name": "gemini_voice",
            "type": "string",
            "default": ""
          },
          "4": {
            "name": "gemini_system_prompt",
            "type": "string",
            "default": ""
          },
          "5": {
            "name": "transcripts",
            "type": "bool",
            "default": true
          },
          "6": {
            "name": "transcript_log",
            "type": "bool",
            "default": true
          },
          "7": {
            "name": "manual_silence_s",
            "type": "u8",
            "default": 10
          },
          "8": {
            "name": "resume_min",
            "type": "u8",
            "default": 60
          },
          "9": {
            "name": "keepalive_s",
            "type": "u8",
            "default": 60
          },
          "10": {
            "name": "echo_measure",
            "type": "bool",
            "default": false
          },
          "11": {
            "name": "barge_in",
            "type": "bool",
            "default": false
          },
          "13": {
            "name": "vad_start",
            "type": "u8",
            "default": 1
          },
          "14": {
            "name": "vad_end",
            "type": "u8",
            "default": 0
          },
          "15": {
            "name": "vad_prefix_ms",
            "type": "u16",
            "default": 0
          },
          "16": {
            "name": "vad_silence_ms",
            "type": "u16",
            "default": 0
          },
          "17": {
            "name": "weather_location",
            "type": "string",
            "default": ""
          },
          "12": {
            "name": "web_search",
            "type": "bool",
            "default": true
          },
          "18": {
            "name": "mcp_url",
            "type": "string",
            "default": ""
          },
          "19": {
            "name": "mcp_max_tools",
            "type": "u8",
            "default": 32
          },
          "20": {
            "name": "briefing_music",
            "type": "string",
            "default": ""
          },
          "21": {
            "name": "briefing_duck",
            "type": "u8",
            "default": 20
          }
        }
      },
      "3": {
        "name": "alerts",
        "key": "string",
        "cached": true,
        "fields": {
          "1": {
            "name": "enabled",
            "type": "bool",
            "default": true
          },
          "2": {
            "name": "source",
            "type": "string",
            "default": ""
          },
          "3": {
            "name": "gain_db",
            "type": "f32",
            "default": 0.0
          }
        }
      },
      "4": {
        "name": "alarms",
        "key": "string",
        "cached": true,
        "fields": {
          "1": {
            "name": "hour",
            "type": "u8",
            "default": 0
          },
          "2": {
            "name": "minute",
            "type": "u8",
            "default": 0
          },
          "3": {
            "name": "days",
            "type": "u8",
            "default": 0
          },
          "4": {
            "name": "at",
            "type": "u32",
            "default": 0
          },
          "5": {
            "name": "label",
            "type": "string",
            "default": ""
          },
          "6": {
            "name": "enabled",
            "type": "bool",
            "default": true
          },
          "7": {
            "name": "tone",
            "type": "string",
            "default": ""
          },
          "8": {
            "name": "snooze_min",
            "type": "u8",
            "default": 9
          },
          "9": {
            "name": "volume",
            "type": "u8",
            "default": 0
          },
          "10": {
            "name": "last_fired",
            "type": "u32",
            "default": 0
          },
          "11": {
            "name": "snooze_until",
            "type": "u32",
            "default": 0
          },
          "12": {
            "name": "kind",
            "type": "u8",
            "default": 0
          },
          "13": {
            "name": "created",
            "type": "u32",
            "default": 0
          },
          "14": {
            "name": "briefing",
            "type": "bool",
            "default": false
          },
          "15": {
            "name": "briefing_start",
            "type": "u8",
            "default": 0
          }
        }
      },
      "5": {
        "name": "reminders",
        "key": "string",
        "cached": true,
        "fields": {
          "1": {
            "name": "hour",
            "type": "u8",
            "default": 0
          },
          "2": {
            "name": "minute",
            "type": "u8",
            "default": 0
          },
          "3": {
            "name": "days",
            "type": "u8",
            "default": 0
          },
          "4": {
            "name": "at",
            "type": "u32",
            "default": 0
          },
          "5": {
            "name": "text",
            "type": "string",
            "default": ""
          },
          "6": {
            "name": "enabled",
            "type": "bool",
            "default": true
          },
          "7": {
            "name": "last_fired",
            "type": "u32",
            "default": 0
          },
          "8": {
            "name": "pending",
            "type": "bool",
            "default": false
          },
          "9": {
            "name": "created",
            "type": "u32",
            "default": 0
          },
          "10": {
            "name": "action",
            "type": "bool",
            "default": false
          }
        }
      }
    }
  },
  "recordings": {
    "hash": 1528652654,
    "path": "/sdcard/db/recordings.ndb",
    "collections": {
      "1": {
        "name": "recordings",
        "key": "string",
        "cached": true,
        "fields": {
          "1": {
            "name": "file",
            "type": "string",
            "default": ""
          },
          "2": {
            "name": "started",
            "type": "u32",
            "default": 0
          },
          "3": {
            "name": "duration_ms",
            "type": "u32",
            "default": 0
          },
          "4": {
            "name": "mode",
            "type": "u8",
            "default": 0
          },
          "5": {
            "name": "sample_rate",
            "type": "u32",
            "default": 0
          },
          "6": {
            "name": "channels",
            "type": "u8",
            "default": 0
          },
          "7": {
            "name": "size",
            "type": "u32",
            "default": 0
          }
        }
      }
    }
  },
  "music": {
    "hash": 98849004,
    "path": "/sdcard/db/music.ndb",
    "collections": {
      "1": {
        "name": "tracks",
        "key": "string",
        "cached": true,
        "fields": {
          "1": {
            "name": "title",
            "type": "string",
            "default": ""
          },
          "2": {
            "name": "artist",
            "type": "string",
            "default": ""
          },
          "3": {
            "name": "album",
            "type": "string",
            "default": ""
          },
          "4": {
            "name": "duration_ms",
            "type": "u32",
            "default": 0
          },
          "5": {
            "name": "file_size",
            "type": "u32",
            "default": 0
          },
          "6": {
            "name": "added_at",
            "type": "u32",
            "default": 0
          },
          "7": {
            "name": "last_played_at",
            "type": "u32",
            "default": 0
          },
          "8": {
            "name": "play_count",
            "type": "u32",
            "default": 0
          },
          "9": {
            "name": "thumbnail",
            "type": "bool",
            "default": false
          }
        }
      }
    }
  }
};
